name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        script: cd ${{ secrets.CARE_DIRECTORY }} && sudo git pull && sudo rm -rf carescripts/migrations/ && poetry update && poetry run ./manage.py  migrate --run-syncdb &&  poetry run ./manage.py loaddata lessons && sudo shutdown -r +1
    - name: Wait for Redeploy
      run: sleep 300s
      shell: bash
    - name: checking deployment
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://dev.nidhoggr.net/graphql'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"query":"query MyQuery {\n  lessons {\n    name\n  }\n}","variables":{}}'
